### ISSUE TITLE
convert to a module

### ISSUE THREAD

**Issue by asbisen** [memoiry/lightML.jl#2]
@memoiry, thanks for doing this. I was wondering if there are any plans to wrap this code such that it could be used as a module? I can assist if that is the intent.

**Comment by memoiry** [comment]
@asbisen Hi, thanks for interesting in the project.  I have not considered a module as this project is still unfinished. But a pull request is welcome, feel free to make a change~

**Comment by memoiry** [comment]
@asbisen Hi, I have wrapped the code into a module, you can access the readme for more information. Also, there is some problem in some implementations and I have tagged it. Feel free to clone it and test.

If you still would like to contribute, there are still a lot of works. Any contribution is definitely helpful. Thanks!
