### ISSUE TITLE
No module named sklearn.datasets

### ISSUE THREAD

**Issue by marekfoltyn** [memoiry/lightML.jl#5]
After installing LightML i can not import LightML:

<img width="645" alt="snimek obrazovky 2017-05-23 v 12 57 28" src="https://cloud.githubusercontent.com/assets/6121995/26351308/6dea075c-3fb7-11e7-9c31-9ac01fc99c3d.png">

**Comment by memoiry** [comment]
Hi,

It's caused by the dependency of python's sklearn package, you can download it by 

```bash
pip install sklearn
```

I recommend downloading it directly, read the source code and import it for testing as this is a package for learning purpose only for now.

**Comment by marekfoltyn** [comment]
> pip install sklearn
> Requirement already satisfied: sklearn in /Library/Python/2.7/site-packages
> Requirement already satisfied: scikit-learn in /Library/Python/2.7/site-packages (from sklearn)

Is LightML using another Python interpreter? I am a bit confused now :)

**Comment by memoiry** [comment]
I think it should be fine now, have you tried to import sklearn.datsets in python REPL?

**Comment by marekfoltyn** [comment]
Yes, it works, but not in LightML. So I guess it is not LightML's problem, but my PC's... :)

**Comment by memoiry** [comment]
I think julia is not calling the right python version with sklearn installed?(maybe you have installed several python environment?) 

you can try to use pycall in your julia environment and find out the answer.

**Comment by marekfoltyn** [comment]
Yes, julia uses different python interpreter. Solved with running pip in the julia-internal python:

`~/.julia/v0.5/Conda/deps/usr/bin/python /Library/Frameworks/Python.framework/Versions/2.7/bin/pip install sklearn`

Thanks for your tips :)
